#!/bin/bash

function _exit()
{
	echo -e "Hasta la vista, baby"
}

trap _exit EXIT

alias .1="cd .."
alias .2="cd ../../"
alias .3="cd ../../../"
alias .4="cd ../../../../"
alias .5="cd ../../../../../"
alias .6="cd ../../../../../../"
alias .7="cd ../../../../../../../"
alias .8="cd ../../../../../../../../"
alias .9="cd ../../../../../../../../../"


alias vi="vim"
