#!/bin/bash

function _exit()
{
	echo -e "Hasta la vista, baby"
}

trap _exit EXIT

alias .1="cd .."
alias .2="cd ../../"
alias .3="cd ../../../"
alias .4="cd ../../../../"
alias .5="cd ../../../../../"
alias .6="cd ../../../../../../"
alias .7="cd ../../../../../../../"
alias .8="cd ../../../../../../../../"
alias .9="cd ../../../../../../../../../"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias la='ls -Al'               # show hidden files
alias ls='ls -hF'		# add colors for filetype recognition
alias lx='ls -lXB'              # sort by extension
alias lk='ls -lSr'              # sort by size
alias lc='ls -lcr'		# sort by change time  
alias lu='ls -lur'		# sort by access time   
alias lr='ls -lR'               # recursive ls
alias lt='ls -ltr'              # sort by date
alias lm='ls -al |more'         # pipe through 'more'
alias tree='tree -Csu'		# nice alternative to 'ls'
alias vi=vim
alias mkdir="mkdir -p"
alias vi="vim"
